name: CI-mac

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-mac:
    # The type of runner that the job will run on
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: pipx install poetry
      - name: build project
        run: |
          poetry config virtualenvs.in-project true
          poetry install
          poetry run pyinstaller --onefile --clean --add-binary 'binaries/mac:.' migaku-player-converter.py
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binary-mac
          path: |
            dist
